[project]
name = "PoT"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.receipt]
path = "contracts/receipt.clar"
depends_on = []
